In [2]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.9595, 0.7097, 0.5792],
        [0.2161, 0.5050, 0.1431],
        [0.2273, 0.9806, 0.1578],
        [0.9859, 0.9409, 0.9280],
        [0.1539, 0.2469, 0.6463]])


In [5]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

A = torch.randn((3, 2))
B = torch.randn((1, 2))

print("A:",A)
print("B:",B)
print("A+B:",(A+B))


A: tensor([[-0.1468,  0.7861],
        [ 0.9468, -1.1143],
        [ 1.6908, -0.8948]])
B: tensor([[-0.3556,  1.2324]])
A+B: tensor([[-0.5024,  2.0185],
        [ 0.5912,  0.1180],
        [ 1.3352,  0.3376]])


In [8]:
C = torch.randn(1,1,12,12)
C

tensor([[[[-1.0586,  0.2207, -0.6669,  0.8000,  0.8453,  0.0246, -0.3749,
           -0.8822, -0.5629, -0.3626, -1.7009,  1.4043],
          [-0.8546,  0.0121,  1.3136,  1.6721, -0.7668, -1.0460,  0.7895,
            2.1033,  0.1130,  0.3631, -0.0771,  0.3913],
          [ 0.8743, -0.4097, -0.2736,  0.6397, -1.0278, -0.5063,  0.4503,
           -0.3944, -0.3365, -1.1310, -0.8041, -0.5476],
          [-0.0415, -0.0878,  2.2665, -1.9948,  0.6058, -0.7967, -0.7414,
           -0.9148, -1.9533,  0.8966, -0.4661, -0.6672],
          [ 0.6394,  0.1586, -1.2346,  0.1045, -0.0632, -1.9473,  0.6125,
           -0.2975, -1.7375, -0.0589, -2.7168, -0.0272],
          [-0.8156,  0.3167, -0.2000,  0.8542,  1.2095, -1.6799, -0.0983,
            0.9393,  0.5755,  0.4824, -1.0046,  0.5371],
          [ 0.7758, -0.6396, -1.1649, -0.0143, -0.1666, -0.3667, -0.4995,
            1.5778,  1.1866,  2.0214,  0.1996,  1.0363],
          [-1.5443, -0.8024, -0.1104, -1.1232,  1.8833,  2.0342, -0.2206,
         

In [9]:
C.reshape(1,1,1,144)

tensor([[[[-1.0586,  0.2207, -0.6669,  0.8000,  0.8453,  0.0246, -0.3749,
           -0.8822, -0.5629, -0.3626, -1.7009,  1.4043, -0.8546,  0.0121,
            1.3136,  1.6721, -0.7668, -1.0460,  0.7895,  2.1033,  0.1130,
            0.3631, -0.0771,  0.3913,  0.8743, -0.4097, -0.2736,  0.6397,
           -1.0278, -0.5063,  0.4503, -0.3944, -0.3365, -1.1310, -0.8041,
           -0.5476, -0.0415, -0.0878,  2.2665, -1.9948,  0.6058, -0.7967,
           -0.7414, -0.9148, -1.9533,  0.8966, -0.4661, -0.6672,  0.6394,
            0.1586, -1.2346,  0.1045, -0.0632, -1.9473,  0.6125, -0.2975,
           -1.7375, -0.0589, -2.7168, -0.0272, -0.8156,  0.3167, -0.2000,
            0.8542,  1.2095, -1.6799, -0.0983,  0.9393,  0.5755,  0.4824,
           -1.0046,  0.5371,  0.7758, -0.6396, -1.1649, -0.0143, -0.1666,
           -0.3667, -0.4995,  1.5778,  1.1866,  2.0214,  0.1996,  1.0363,
           -1.5443, -0.8024, -0.1104, -1.1232,  1.8833,  2.0342, -0.2206,
           -0.2307, -0.8079, -1.0455, 